## # #  # # ##
##  Powder  ##
## # #  # # ##

## Current version of this config.yml. Should not be edited.
configVersion: 4

## Maximum amount of Powders that a user can be using at one time
maxPowdersAtOneTime: 3

## If true, users can use the same Powder multiple times at once
allowSamePowdersAtOneTime: true

## Minimum time allowed between usage of Powders
secondsBetweenPowderUsage: 5

## Powders per page in any formatted list
## (/powder help, /powder list, etc)
pageLength: 7

## If true, the console will send a list of all Powders loaded on startup/reload
listOfLoadedPowders: true

## If true, Powders will be loaded when they are created, instead of being loaded at startup
## This will sometimes make Powder creation longer, but will reduce memory usage significantly if you have 50+ Powders, and will make startup load immediate
fastMode: false

## If true, the main Powder creation task will be performed in a separate thread, resulting in an almost 100% performance increase 
## This mode has been thoroughly tested, but due to the nature of asynchronous tasks, use at your own risk
asyncMode: false

## If true, Powders are divided into categories
categoriesEnabled: true

## List of categories
## {total} -- Number of Powders in this category
## {total-hidden} -- Number of unhidden Powders in this category
categories:
  Emojis:
    desc: '{total} Emojis'
  Flags:
    desc: '{total} Flags of Countries'
  Effects:
    desc: '{total} Random Particles / Effects'
  Songs:
    desc: '{total} Songs with Effects'
  Crowns:
    desc: '{total} Particles Around your Head'

## Max allowed to create per user with the powder.create permission
## powder.createany is unlimited
maxCreated: 100

## Settings for Towny and PlotSquared for maximum amount of created Powders within an area
towny:
  ## Maximum for a town, regardless of town size
  maxCreatedTown: 40
plotsquared:
  ## Maximum for a single plot area (ignoring merging)
  maxCreatedPlot: 20

## Use storage to persist Powders upon logout (or when switching server if using MySQL)
## If none are enabled, Powders attached to entities will unload alongside chunk unloading
## Only enable one storage method at a time. If you aren't sure which one to pick, use SQLite
storage:
  mysql:
    use: false
    host: localhost
    port: 3306
    database: minecraft
    table: powders
    username: root
    password: password
  sqlite:
    use: false
    file: powders.db
  json:
    use: false
    file: powders.json  

## Locale to use (from locale source folder)
locale: 'en-us.yml'

## Files/URLs to source Powder configuration files from
powderSources:
  - 'powders.yml'